abbreviations = {
    'acc': 'accident',
    'acci': 'accident',
    'accid': 'accident',
    'auth': 'authorized',
    'bac': 'blood alcohol',
    'betwn': 'between',
    'canc': 'cancel',
    'cdl': 'commercial drivers license',
    'chng': 'change',
    'comb': 'combined',
    'cond': 'condition',
    'const': 'construction',
    'cont': 'controlled',
    'conv': 'conviction',
    'ctrl': 'control',
    'd': '',
    'def': 'defective',
    'dept': 'department',
    'dev': 'device',
    'disp': 'display',
    'displ': 'display',
    'dist': 'distance',
    'distr': 'distribute',
    'dlr': 'dealer',
    'dmv': 'department of motor vehicles',
    'dob': 'date of birth',
    'dr': 'drive',
    'drgs': 'drugs',
    'driv': 'drive',
    'drvg': 'driving',
    'dui': 'driving under the influence',
    'dwr': 'driving while revoked',
    'dws': 'driving while suspended',
    'ed': 'education',
    'emer': 'emergency',
    'empl': 'employee',
    'eng': 'engine',
    'equip': 'equipment',
    'etc': '',
    'fin': 'financial',
    'ft': 'feet',
    'hab': 'habitual',
    'haz': 'hazardous',
    'hr': 'hour',
    'hwy': 'highway',
    'i': '',
    'ie': '',
    'imp': 'improper',
    'infl': 'influence',
    'inj': 'injury',
    'ins': 'insurance',
    'insp': 'inspection',
    'judg': 'judgment',
    'lic': 'license',
    'lost/': 'lost',
    'lt': 'left',
    'maint': 'maintain',
    'manuf': 'manufacturer',
    'mat': 'material',
    'mcyc': 'motorcycle',
    'mfr': 'manufacturer',
    'misrep': 'misrepresentation',
    'mv': 'motor vehicle',
    'mvr': 'motor vehicle record',
    'occup': 'occupant',
    'oper': 'operator',
    'othr': 'other',
    'parkd': 'parked',
    'pd': 'property damage',
    'ped': 'pedestrian',
    'perm': 'permit',
    'pi': 'personal injury',
    'pkg': 'parking',
    'priv': 'privilege',
    'prob': 'probation',
    'prog': 'program',
    'proh': 'prohibited',
    'proj': 'projecting',
    'prp': 'property',
    'pt': '',
    'pvt': 'private',
    'r.o.w': 'right of way',
    'rd': 'road',
    're': '',
    'recd': 'record',
    'reg': 'registration',
    'rein': 'reinstatement',
    'req': 'required',
    'resp': 'responsibility',
    'restr': 'restriction',
    'ret': 'return',
    'rev': 'revoked',
    'rpt': 'report',
    'rr': 'railroad',
    'rt': 'right',
    'schl': 'school',
    'sdwk': 'sidewalk',
    'st': 'street',
    'sub': 'substance',
    'subst': 'substance',
    'surr': 'surrender',
    'susp': 'suspension',
    'svc': 'standard vehicle code',
    'thru': 'through',
    'traf': 'traffic',
    'trans': 'transportation',
    'uncl': 'unclassified',
    'und': 'under',
    'undr': 'under',
    'veh': 'vehicle',
    'viol': 'violation',
    'w': 'with',
    'w/o': 'without',
    'wrng': 'warning',
    'yld': 'yield',
    'yr': 'year',
    'yrs': 'years',
    '“': '',
    '”': ''
}
